### PR TITLE
Further Bug Fix / Feature Request pass

### PR DESCRIPTION
**Pull request by Sleet01**
Starting out with Thweek, who is now fully-functional (albeit not completely tested with every pilot).  See commit notes for details.

Other fixes / updates to follow.

### CODE REVIEW

**Comment by cbmainz** [comment]
Is Mimicked or Shadowed assign automatically by the IA?

I don't fully understand:

> 3) Does *not* assign Conditions based on Mimicked pilot abilities (via
Overriding "Condition()")

> 4) *Does* allow native Condition-applying pilot abillities to continue functioning.

**Comment by Sleet01** [comment]
@cbmainz The default state is Shadowed so the AI will choose that unless the human player switches the AI's Thweek to "Mimicked".  That UI element is available until the end of the Setup phase.

Sorry for the terseness: what I meant is, I override the global function Condition(...) within the context of Thweek's Mimicked condition in order to prevent Thweek's copied abilities from ever assigning a Condition card to a target.  For instance, if Thweek uses Mimicked on Kylo Ren, he gains Kylo Ren's pilot ability to assign "I'll Show You The Dark Side" condition cards (by running Kylo Ren's .init() function on himself).  However, Thweek's Mimicked card explicitly states that Thweek can never use a Mimicked pilot ability to assign a condition card.

The cleanest solution I could come up with was to do a one-time override of the Condition(...) function within the Mimicked code - that's the "3." above.  It wraps the actual Condition(...) function in a check that only assigns a Condition card if the assigning ship is *not* Thweek.  But if any other ship makes a call to Condition(...), that call is passed through to the actual code and works as per usual - that's the "4."

I chose this approach because it's relatively compact and allows us to copy abilities by calling the target ship's .init() on Thweek, the method used by other ability-copying ships like the IG-2000 upgrade card and the Hound's Tooth title.  There's only one issue: if one team has a Thweek using Shadowed, and the other team has a Thweek using Mimicked *on* that Thweek, then nothing really happens and the AI would do an infinite loop (having chosen Thweek as the Mimicked target once, it will continue to do so).  My solution was to allow one more pass through the Mimicked init path but remove the other Thweek from the list of valid Mimicked targets.  It's a little convoluted but makes the AI version of Thweek work correctly in mirror matches.

**Comment by cbmainz** [comment]
@Sleet01 thanks for clarification. 

I test Thweek as IA and he chooses always the lowest pilot skill with 'Shadowed'. And when 'Mimicked' is selected, it also chooses most of the time the pilot with the lowest skill.

**Comment by Sleet01** [comment]
@cbmainz Yeah, I just noticed that.  Currently there's no real AI selection intelligence for Thweek's choice.  I'll see if I can smarten it up.

**Pull request merged**
