### PR TITLE
Working fix for Tournament List cross-origin issue on Chrome (and others)

### PR DESCRIPTION
**Pull request by Sleet01**
I didn't hear back on the issue for this, so I decided to submit the PR.  See the individual commits for details, but this fixes the issue where Chrome would not display tournament lists due to XWS-Bench sourcing them from an unsecure http:// URL.  This is only going to become a bigger issue as other browsers start blocking or warning on this type of resource.

The fix I implemented was to set up a Linux-hosted script (3, actually) that pulls down the tournaments list, diffs it against the previous version, and wgets any new lists that have been uploaded since the last time it ran.  It then commits these lists to the new /tournament dir, from which XWS-Bench reads the json files and serves them via its SSL-certified URL, bypassing the cross-origin issue.

<<< WARNING >>>
Before approving this Pull Request, you need to add the following RSA public key to the list of authorized keys for this repo.  I personally will not use the key for my normal commits, but the automated script needs it in order to be able to push list updates to the gh-pages branch.

<<< key (copy everything from the 's' of 'ssh' to the 'm of '.com') >>>
`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUC0A3PMubFMRQLtZILMloaCcNaSphqVszi6aLn0ouC83g76wxPnDRpfA6OqZCCkpQyyTbhh7wxoFJ08IsS/2U1wPaAhkem7WcjFQ2juxZ8ZE6WBVZGh3UfEIH/jT/oiIlaCawY8ppU8BL2GxR45XP6dKWvajyJ8v9IoeUfrTibiUfgKIPqbbj4wbpjcSIo3Xo44aBEtRulPcpn4h5iuLB06gtTv8lkI+hLWkA8VY1/UqzrSbfN95QSYGmq+hohGV1TXnnI44qBaCRKBME5ysq5PfESF/yUJfLJX7FLM/bLxUvB9+iYQiy3ZUHlEN+gEvHhyOb3zQPQrt5n3rlf13ck9Si1o2IG8SZrRdeAzbjKokt8SLW3Oo5lCft8CTJ0yz3RE2K5NleV+8v/6zueQrVIGgi13aoXxeQVuhGj5WpEffKU+O74KngDfwPCmRX/q/HwVR5YqP0z6VzZ3QUwW/m+9idE7gtuMcnTtqtMN8Y4liuEiSAtVm00khWHjX7SYoe+vqvLs4WLmMrtTgPVjTd16qexTsmTVAnhKSRI4ja+XV5GK6ncsGapl+EpuAuIGBxFfKqv7oLgQEtXLwkw/ooV3TGO1MeLCF8EY159tRMkF9V/qJKLDPkGlkXkFOlCi/W6Kbe0xHYP1bGD+gFSrRT7ya38Zyd+Ea+pPzQraI51w== sleet01@hotmail.com`
<<< end key >>>

I plan to host the automated scripts, but if someone else is interested, here are the cron settings I'm using to run them:

<<< crontab entries >>>

```
# m h  dom mon dow   command
55 23   *   *   *       cd /home/martin/projects/bench/tournament/ && ./refresh_recent_files.sh
0 */4   *   *   *       cd /home/martin/projects/bench/tournament/ && ./update_tournaments.sh > ./latest_update.log 2>&1
5 */4   *   *   *       cd /home/martin/projects/bench/tournament/ && git add ./latest_update.log && git commit -m "Updating log file" && git push origin gh-pages
```

<<< end crontab entries >>>

Before approving, you can try out the local-file version here: https://sleet01.github.io/bench/main.html#selectphase

### CODE REVIEW

**Comment by Sleet01** [comment]
Recent updates also added a refresh script that re-downloads more recent listings (default: 100) since they are often updated after initial entry to reflect final results.  Also updated some pilots due to List Juggler import issues.

**Comment by baranidlo** [comment]
@Sleet01: please update the scheduling of the script to once per day, so that it won't be generating too many commits. Thx.

**Comment by Sleet01** [comment]
@baranidlo Will do.  I will locally disable the cron jobs until these updates go live in gh-pages, then enable them once per day at midnight.

**Comment by Sleet01** [comment]
For reference, the new crontab settings:

    # 55 23 *   *   *       cd /home/bench-updater/projects/bench/tournament/ && ./refresh_recent_files.sh 300
    # 0 0   *   *   *       cd /home/bench-updater/projects/bench/tournament/ && ./update_tournaments.sh > ./latest_update.log 2>&1
    # 5 0   *   *   *       cd /home/bench-updater/projects/bench/tournament/ && git add ./latest_update.log && git commit -m "Updating log file" && git push origin gh-pages

**Pull request merged**
